
=== About DataStax

DataStax, the leading distributed database management system, delivers Apache Cassandra to the world’s most innovative enterprises. Datastax is built to be agile, always-on, and predictably scalable to any size.

DataStax has more than 500 customers in 45 countries including leaders such as Netflix, Adobe, Intuit, and eBay and spans verticals including web, financial services, telecommunications, logistics, and government. Based in Santa Clara, Calif., DataStax is backed by industry-leading investors including Lightspeed Venture Partners, Meritech Capital, and Crosslink Capital. For more information, visit http://www.datastax.com[DataStax.com] or follow us https://twitter.com/DataStax[@DataStax] and https://twitter.com/DataStaxEU[@DataStaxEU].

//===== About DataStax Enterprise

DataStax Enterprise:: DataStax Enterprise (DSE), built on Apache Cassandra™, delivers what Internet Enterprises need to compete in today’s high-speed, always-on data economy. With in-memory computing capabilities, enterprise-level security, fast and powerful integrated analytics and enterprise search, visual management, and expert support, DataStax Enterprise is the leading distributed database choice for online applications that require fast performance with no downtime.

DataStax OpsCenter:: DataStax OpsCenter makes it easy to manage Apache Cassandra and DataStax Enterprise clusters by giving administrators, architects and developers an at-a-glance view of the system from a centralized dashboard. OpsCenter installs seamlessly and gives system operators the flexibility to monitor and manage even the most complex workloads with ease from any web browser.
