
=== Configuring Multi-Region Data Centers in Azure

There are two ways to configure multi-region DSE/Cassandra clusters in Azure:

. Instance Level Public IP (PIP)
. VNet-to-VNet

http://msdn.microsoft.com/en-us/library/azure/dn690118.aspx[Instance-Level Public IP Addresses] can be assigned to each Cassandra cluster node effectively allowing all nodes to speak to each other over public internet. Drawbacks in comparison to VNet-to-VNet setup are:

 * Need to enable node and Cassandra security (encryption and authentication). Unlike VNet-to-VNet setup, nodes and ports are publically accessible.
 * Access to sufficient PIPs usually requires special approval from Azure support.

http://msdn.microsoft.com/en-us/library/azure/dn690122.aspx[VNet-to-VNet] is VPN between two Azure VNets which could be on any Azure region or between Azure VNet and customer premises. It has some drawbacks in comparison to PIP:

 * VPN gateways are a potential bottleneck in large deployments
 * VPN gateway failure results in data centers disconnection. Note that this is acceptable for DSE, which has been designed to tolerate intermittent network interruptions.
 * Need to maintain N*(N-1)/2 VPN connections with N*(N-1) VPN gateways, where N is number of vnets. As number of vnets grow, it may become a problem.
