
==== Azure Multi-region Setup using VNet-to-VNet

:toc:

This tutorial shows how to setup a multi-region Cassandra cluster between West Europe (WEU) and North Europe (NEU) in Azure using VNet-to-VNet VPN. These scripts set up two data centers, each with three nodes. Modify the loop parameters to increase the number of nodes in each data center.

===== Setup Network

|===
|Network |Local Network Site |Remote (Virtual) Network Site |Azure Region / DC

|cassandra-xdc-neu
|10.1.1.0/24
|10.1.2.0/24
|NEU (North EU)

|cassandra-xdc-weu
|10.1.2.0/24
|10.1.1.0/24
|WEU (West EU)
|===

.Create affinity groups
[source,powershell]
----
New-AzureAffinityGroup -Name "CassandraGroup-NEU" -Label "DataStax" -Location "North Europe"
New-AzureAffinityGroup -Name "CassandraGroup-WEU" -Label "DataStax" -Location "West Europe"
----

[NOTE]
====
This next step can be performed via the Azure Portal or via the cross-platform tools, there is no PowerShell equivalent.
====

.Create VNets
[source,bash]
----
azure network vnet create --affinity-group "CassandraGroup-NEU" --address-space 10.1.2.0 --cidr 24 cassandra-xdc-neu
azure network vnet create --affinity-group "CassandraGroup-WEU" --address-space 10.1.1.0 --cidr 24 cassandra-xdc-weu
----

Follow instructions from this tutorial, at step 8 use commands below:
http://blogs.technet.com/b/aviraj/archive/2014/05/16/microsoft-azure-configure-cross-subscription-vnet-to-vnet-connectivity-in-azure.aspx

.Configure gateway shared keys (Step 8):
[source,powershell]
----
Set-AzureVNetGatewayKey -VNetName cassandra-xdc-weu -LocalNetworkSiteName cassandra-xdc-neu -SharedKey CA33A7DA
Set-AzureVNetGatewayKey -VNetName cassandra-xdc-neu -LocalNetworkSiteName cassandra-xdc-weu -SharedKey CA33A7DA
----

===== Setup Instances

Use following instance setup:

|===
|Node |IP |Azure Region / DC
|neu0 |10.0.1.10    |NEU
|neu1   |10.0.1.11  |NEU
|neu2   |10.0.1.12  |NEU
|weu0   |10.0.2.10  |WEU
|weu1   |10.0.2.11  |WEU
|weu2   |10.0.2.12  |WEU
|===

In each region (Affinity Group) create new CloudService and storage account.
[source,powershell]
----
New-AzureService -ServiceName "cassandra-neu" -AffinityGroup "CassandraGroup-NEU"
New-AzureService -ServiceName "cassandra-weu" -AffinityGroup "CassandraGroup-WEU"

New-AzureStorageAccount -StorageAccountName "cassandraneu" -AffinityGroup "CassandraGroup-NEU"
New-AzureStorageAccount -StorageAccountName "cassandraweu" -AffinityGroup "CassandraGroup-WEU"
----

Provision 3 VM instances with static internal IPs (Set-AzureStaticVNetIP command) in each CloudService.
[source,powershell]
----
# Get subscription name
$subscription = Get-AzureSubscription -Current | select -expand SubscriptionName

# Set default storage account to North EU
Set-AzureSubscription -SubscriptionName $subscription -CurrentStorageAccountName "cassandraneu"

# Create instances in North EU affinity group
for($i=0; $i -le 2; $i++)
{
    $sshPort = 10000 + $i
    $staticIP = 10+$i

    New-AzureVMConfig -Name "cassandra-neu$i" -ImageName "5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-65-20140606" -InstanceSize "A7" | `
        Add-AzureProvisioningConfig -Linux -LinuxUser "datastax" -Password "Cassandra123" -NoSSHEndpoint | `
        Add-AzureEndpoint -LocalPort 22 -Name 'SSH' -Protocol tcp -PublicPort "$sshPort" | `
        Set-AzureSubnet -SubnetNames "Subnet-1" | `
        Set-AzureStaticVNetIP -IPAddress "10.0.1.$staticIP" | `
        New-AzureVM -ServiceName "cassandra-neu" -VNetName "cassandra-xdc-neu"
}

# Set default storage account to West EU
Set-AzureSubscription -SubscriptionName $subscription -CurrentStorageAccountName "cassandraweu"

# Create instances in West EU affinity group
for($i=0; $i -le 2; $i++)
{
    $sshPort = 10000 + $i
    $staticIP = 10+$i

    New-AzureVMConfig -Name "cassandra-weu$i" -ImageName "5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-65-20140606" -InstanceSize "A7" | `
        Add-AzureProvisioningConfig -Linux -LinuxUser "datastax" -Password "Cassandra123" -NoSSHEndpoint | `
        Add-AzureEndpoint -LocalPort 22 -Name 'SSH' -Protocol tcp -PublicPort "$sshPort" | `
        Set-AzureSubnet -SubnetNames "Subnet-1" | `
        Set-AzureStaticVNetIP -IPAddress "10.0.2.$staticIP" | `
        New-AzureVM -ServiceName "cassandra-weu" -VNetName "cassandra-xdc-weu"
}
----

If there are already instances running, it is possible to set or update the static IP. For more info on internal static IPs see http://msdn.microsoft.com/en-us/library/azure/dn630228.aspx


===== Setup Cassandra

Install Cassandra on all nodes following RHEL setup guide or using OpsCenter.

In `cassandra.yaml` set followings:
[source,yaml]
----
listen_address: <local static IP of the node>
rpc_address: 0.0.0.0
seeds: <weu0 local ip>, <neu0 local ip>
endpoint_snitch: GossipingPropertyFileSnitch
data_directories: /mnt/resource/cassandra/data
commitlog_directory: /mnt/resource/cassandra/commitlog
saved_caches_directory: /mnt/resource/cassandra/saved_caches
----

Configure +GossipingPropertyFileSnitch+ in `cassandra-rackdc.properties` file:
[source,bash]
----
dc=WEU # and NEU respectively for nodes in North Europe
rack=RACK1
----

Add following lines to `/etc/hosts` file on all nodes:
----
10.0.1.10 neu0
10.0.1.11 neu1
10.0.1.12 neu2
10.0.2.10 weu0
10.0.2.11 weu1
10.0.2.12 weu2
----
