
==== Azure Multi-region Setup using Instance Level Public IPs

:toc:

Following tutorial shows how to setup multi-region Cassandra cluster between West Europe (WEU) and North Europe (NEU) in Azure using Public IPs (PIP).

===== Setup Network

Public IP requires Regional (wide) VNet, which is different from Affinity Group VNet. By default Azure Portal will create a Regional VNet.

In Azure portal create two regional VNets +New > Virtual Network > Custom Create+ with following settings, leaving all others empty:

|===
|VNet Name |Region | IP address space

|cassandra-rvnet-neu
|North Europe
|10.2.1.0/24

|cassandra-rvnet-weu
|West Europe
|10.2.2.0/24
|===

===== Setup Instances

In each DC (Region) create a new CloudService and storage accounts.

[source,powershell]
----
New-AzureService -ServiceName "cassandra-neu" -Location "North Europe"
New-AzureService -ServiceName "cassandra-weu" -Location "West Europe"

New-AzureStorageAccount -StorageAccountName "cassandraneu" -Label "DataStax" -Location "North Europe"
New-AzureStorageAccount -StorageAccountName "cassandraweu" -Label "DataStax" -Location "West Europe"
----

Provision 3 VM instances with internal static IP (Set-AzureStaticVNetIP command) and public IP (Set-AzurePublicIP command) in each DC.

[source,powershell]
----
# Get subscription name
$subscription = Get-AzureSubscription -Current | select -expand SubscriptionName

# Set default storage account to North EU
Set-AzureSubscription -SubscriptionName $subscription -CurrentStorageAccountName "cassandraneu"

# Create instances in North EU region
for($i=0; $i -le 2; $i++)
{
    $sshPort = 10000 + $i
    $staticIP = 10+$i

    New-AzureVMConfig -Name "cassandra-neu$i" -ImageName "5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-65-20140606" -InstanceSize "A7" | `
        Add-AzureProvisioningConfig -Linux -LinuxUser "datastax" -Password "Cassandra123" -NoSSHEndpoint | `
        Add-AzureEndpoint -LocalPort 22 -Name 'SSH' -Protocol tcp -PublicPort "$sshPort" | `
        Set-AzureSubnet -SubnetNames "Subnet-1" | `
        Set-AzureStaticVNetIP -IPAddress "10.2.1.$staticIP" | `
        Set-AzurePublicIP -PublicIPName Cassandra | `
        New-AzureVM -ServiceName "cassandra-neu" -VNetName "cassandra-rvnet-neu"
}

# Set default storage account to West EU
Set-AzureSubscription -SubscriptionName $subscription -CurrentStorageAccountName "cassandraweu"

# Create instances in West EU region
for($i=0; $i -le 2; $i++)
{
    $sshPort = 10000 + $i
    $staticIP = 10+$i

    New-AzureVMConfig -Name "cassandra-weu$i" -ImageName "5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-65-20140606" -InstanceSize "A7" | `
        Add-AzureProvisioningConfig -Linux -LinuxUser "datastax" -Password "Cassandra123" -NoSSHEndpoint | `
        Add-AzureEndpoint -LocalPort 22 -Name 'SSH' -Protocol tcp -PublicPort "$sshPort" | `
        Set-AzureSubnet -SubnetNames "Subnet-1" |
        Set-AzureStaticVNetIP -IPAddress "10.2.2.$staticIP" | `
        Set-AzurePublicIP -PublicIPName Cassandra | `
        New-AzureVM -ServiceName "cassandra-weu" -VNetName "cassandra-rvnet-weu"
}
----

If there are already instances running, PublicIP addresses can be assigned for all VMs in the cloud service or individually using following commands:

[source,powershell]
----
# all instances in CS
Get-AzureVM -ServiceName cassandra-weu | Set-AzurePublicIP -PublicIPName Cassandra | Update-AzureVM
# single instance
Get-AzureVM -ServiceName cassandra-weu -Name cassandra-weu2 | Set-AzurePublicIP -PublicIPName Cassandra | Update-AzureVM
----

Get list of PIPs for each VM instance:

[source,powershell]
----
Get-AzureVM -ServiceName cassandra-weu

# ...
# PublicIPAddress             : 23.100.2.11
# ...
# PublicIPAddress             : 23.100.2.12
# ...
----

All ports are accessible on public IPs without mapping.

===== Setup Cassandra

Install Cassandra on all nodes following RHEL setup guide or using OpsCenter.

In order to communicate in Azure multi-region environment using PIPs, Cassandra needs to know both - local and public IPs (broadcast).

In `cassandra.yaml` set followings:

[source,yaml]
----
listen_address: <local static IP of the node>
broadcast_address: <assigned PIP address of this node>
rpc_address: 0.0.0.0
seeds: <weu0 PIP, neu0 PIP>
endpoint_snitch: GossipingPropertyFileSnitch
data_directories: /mnt/resource/cassandra/data
commitlog_directory: /mnt/resource/cassandra/commitlog
saved_caches_directory: /mnt/resource/cassandra/saved_caches
----

Configure +GossipingPropertyFileSnitch+ in `cassandra-rackdc.properties` file:

[source,bash]
----
dc=WEU # and NEU respectively for nodes in North Europe
rack=RACK1
----

TIP: Autoconfiguration could be possible in future using WAAgent info. Azure role topology information is captured by WAAgent daemon running on the node and dumped into /var/lib/waagent/SharedConfig.xml on each instance. However, this file does not contain PIP yet (only local and SLB IP). See http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-agent-user-guide/ and https://github.com/Azure/WALinuxAgent for more info on WAAgent.
