=== Azure Multi-region Setup using VNet-to-VNet

:toc:

Following tutorial shows how to setup multi-region Cassandra cluster between West Europe (WEU) and North Europe (NEU) in Azure using VNet-to-VNet VPN.

We will use following setup:

==== Setup Network

We will use following network setup:

|===
|Network |Local Network Site |Remote (Virtual) Network Site |Azure Region / DC

|cassandra-xdc-neu
|10.1.1.0/24
|10.1.2.0/24
|NEU (North EU)

|cassandra-xdc-weu
|10.1.2.0/24
|10.1.1.0/24
|WEU (West EU)
|===

Create affinity groups:
[source,powershell]
----
New-AzureAffinityGroup -Name "CassandraGroup-NEU" -Label "DataStax" -Location "North Europe"
New-AzureAffinityGroup -Name "CassandraGroup-WEU" -Label "DataStax" -Location "West Europe"
----

Create VNets (there's no PowerShell cmdlet for that, use xplatform CLI or Portal):
[source,powershell]
----
azure network vnet create --affinity-group "CassandraGroup-NEU" --address-space 10.1.2.0 --cidr 24 cassandra-xdc-neu
azure network vnet create --affinity-group "CassandraGroup-WEU" --address-space 10.1.1.0 --cidr 24 cassandra-xdc-weu
----

Follow instructions from the following tutorial, at step 8 use commands below:
http://blogs.technet.com/b/aviraj/archive/2014/05/16/microsoft-azure-configure-cross-subscription-vnet-to-vnet-connectivity-in-azure.aspx

Configure gateway shared keys (Step 8):
[source,powershell]
----
Set-AzureVNetGatewayKey -VNetName cassandra-xdc-weu -LocalNetworkSiteName cassandra-xdc-neu -SharedKey CA33A7DA
Set-AzureVNetGatewayKey -VNetName cassandra-xdc-neu -LocalNetworkSiteName cassandra-xdc-weu -SharedKey CA33A7DA
----

==== Setup Instances

We will use following instance setup:

|===
|Node |IP |Azure Region / DC
|neu0 |10.0.1.10    |NEU
|neu1   |10.0.1.11  |NEU
|neu2   |10.0.1.12  |NEU
|weu0   |10.0.2.10  |WEU
|weu1   |10.0.2.11  |WEU
|weu2   |10.0.2.12  |WEU
|===

In each region (Affinity Group) create new CloudService and storage account.
[source,powershell]
----
New-AzureService -ServiceName "cassandra-neu" -AffinityGroup "CassandraGroup-NEU"
New-AzureService -ServiceName "cassandra-weu" -AffinityGroup "CassandraGroup-WEU"
 
New-AzureStorageAccount -StorageAccountName "cassandraneu" -AffinityGroup "CassandraGroup-NEU"
New-AzureStorageAccount -StorageAccountName "cassandraweu" -AffinityGroup "CassandraGroup-WEU"
----

Provision 3 VM instances with static internal IPs (Set-AzureStaticVNetIP command) in each CloudService.
[source,powershell]
----
# Get subscription name
$subscription = Get-AzureSubscription | select -expand CurrentStorageAccountName
  
# Set default storage account to North EU
Set-AzureSubscription -SubscriptionName $subscription -CurrentStorageAccountName "cassandraneu"
  
# Create instances in North EU affinity group
for($i=0; $i -le 2; $i++)
{
    $sshPort = 10000 + $i
    $staticIP = 10+$i
 
    New-AzureVMConfig -Name "cassandra-neu$i" -ImageName "5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-65-20140606" -InstanceSize "A7" | `
        Add-AzureProvisioningConfig -Linux -LinuxUser "datastax" -Password "Cassandra123" -NoSSHEndpoint | `
        Add-AzureEndpoint -LocalPort 22 -Name 'SSH' -Protocol tcp -PublicPort "$sshPort" | `
        Set-AzureSubnet -SubnetNames "Subnet-1" | `
        Set-AzureStaticVNetIP -IPAddress "10.0.1.$staticIP" | `
        New-AzureVM -ServiceName "cassandra-neu" -VNetName "cassandra-xdc-neu"
}
  
# Set default storage account to West EU
Set-AzureSubscription -SubscriptionName $subscription -CurrentStorageAccountName "cassandraweu"
  
# Create instances in West EU affinity group
for($i=0; $i -le 2; $i++)
{
    $sshPort = 10000 + $i
    $staticIP = 10+$i
  
    New-AzureVMConfig -Name "cassandra-weu$i" -ImageName "5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-65-20140606" -InstanceSize "A7" | `
        Add-AzureProvisioningConfig -Linux -LinuxUser "datastax" -Password "Cassandra123" -NoSSHEndpoint | `
        Add-AzureEndpoint -LocalPort 22 -Name 'SSH' -Protocol tcp -PublicPort "$sshPort" | `
        Set-AzureSubnet -SubnetNames "Subnet-1" | `
        Set-AzureStaticVNetIP -IPAddress "10.0.2.$staticIP" | `
        New-AzureVM -ServiceName "cassandra-weu" -VNetName "cassandra-xdc-weu"
}
----

If you already have instance running, it is possible to set or update static IP. For more info on internal static IPs see http://msdn.microsoft.com/en-us/library/azure/dn630228.aspx


==== Setup Cassandra

Install Cassandra on all nodes following RHEL setup guide or using OpsCenter.

In `cassandra.yaml` set followings:
[source,yaml]
----
listen_address: <local static IP of the node>
rpc_address: 0.0.0.0
seeds: <weu0 local ip>, <neu0 local ip>
endpoint_snitch: GossipingPropertyFileSnitch
data_directories: /mnt/resource/cassandra/data
commitlog_directory: /mnt/resource/cassandra/commitlog
saved_caches_directory: /mnt/resource/cassandra/saved_caches
----

Configure +GossipingPropertyFileSnitch+ in `cassandra-rackdc.properties` file:
[source,bash]
----
dc=WEU # and NEU respectively for nodes in North Europe
rack=RACK1
----

Add following lines to `/etc/hosts` file on all nodes:
----
10.0.1.10 neu0
10.0.1.11 neu1
10.0.1.12 neu2
10.0.2.10 weu0
10.0.2.11 weu1
10.0.2.12 weu2
----

==== Results

Start cassandra and you should see:
----
[datastax@cassandra-neu1 datastax]# nodetool status
Datacenter: NEU
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Owns (effective)  Host ID                               Token                                    Rack
UN  10.0.1.12  59.04 KB   38.9%             c84a9d01-d8c9-4827-82ce-025efcda7cbd  -9217384904338704508                     RAC1
UN  10.0.1.11  61.03 KB   40.6%             d5ad0a36-64e4-44cd-a427-ab2f6b0366e4  -9194586200473097853                     RAC1
UN  10.0.1.10  61.03 KB   40.6%             d5ad0a36-64e4-44cd-a427-c93d992bffed  -9184918462767730700                     RAC1
Datacenter: WEU
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Owns (effective)  Host ID                               Token                                    Rack
UN  10.0.2.12  55.37 KB   41.7%             c186d079-570f-4ab4-bb63-ab2f6b0366e4  -9181193292507748589                     RAC1
UN  10.0.2.11  71.52 KB   40.4%             908ecf9c-b993-4dc4-8303-6dc2c7837bd7  -9194586200473097853                     RAC1
UN  10.0.2.10  40.95 KB   38.4%             936dd280-c61d-4ca2-9434-0bc2315297b2  -9167191426354193827                     RAC1
----

Stress test results:
----
# cassandra-stress -R NetworkTopologyStrategy -e LOCAL_ONE -O "WEU:2,NEU:2"
...
 
Averages from the middle 80% of values:
interval_op_rate          : 15292
interval_key_rate         : 15292
latency median            : 0.7
latency 95th percentile   : 3.2
latency 99.9th percentile : 109.0
Total operation time      : 00:01:07
----
